let paresrTable={
    "Statements":{"(":["Statement","Statements"] , "!":["Statement","Statements"] , "T_Id":["Statement","Statements"] , "T_Decimal":["Statement","Statements"] , "T_Hexadecimal":["Statement","Statements"] , "T_String":["Statement","Statements"] , "T_Character":["Statement","Statements"] , "T_True":["Statement","Statements"] , "T_False":["Statement","Statements"], "+":["Statement","Statements"] , "-":["Statement","Statements"], ";":["Statement","Statements"] , "T_If":["Statement","Statements"] , "T_For":["Statement","Statements"] , "T_Bool":["Statement","Statements"] , "T_Int":["Statement","Statements"] , "T_Char":["Statement","Statements"],"T_Void":["Statement","Statements"]  , "T_Print":["Statement","Statements"],"$":["#"]},
    "Statement":{"(":["S",";"] , "!":["S",";"] , "T_Id":["S",";"] , "T_Decimal":["S",";"] , "T_Hexadecimal":["S",";"] , "T_String":["S",";"] , "T_Character":["S",";"] , "T_True":["S",";"] , "T_False":["S",";"], "+":["S",";"] , "-":["S",";"], ";":[";"] , "T_If":["IF"] , "T_For":["For"] , "T_Bool":["Type","T_Id","Def"] , "T_Int":["Type","T_Id","Def"] , "T_Char":["Type","T_Id","Def"],"T_Void":["Type","T_Id","Def"]  , "T_Print":["Print",";"]},
    "Type":{"T_Int":["T_Int"] , "T_Char":["T_Char"] , "T_Bool":["T_Bool"] , "T_Void":["T_Void"]},
    "S":{"(":[["A","B","P'"],["P'"]], "T_Id":[["A","B","P'"],["P'"]] , "T_Decimal":["P'"] , "T_Hexadecimal":["P'"] , "T_String":["P'"] , "T_Character":["P'"] , "T_True":["P'"] , "T_False":["P'"] , "+":["P'"] , "-":["P'"], "!":["P'"]},
    "A":{"(":["(","T_Id",")","A'"] , "T_Id":["T_Id","A'"] },
    "B":{"=":["="],"+":["+","="], "-":["-","="] , "*":["*","="], "/":["/","="], "%":["%","="]},
    "A'":{"=":[["B","A","A'"],["#"]],"+":[["B","A","A'"],["#"]] , "-":[["B","A","A'"],["#"]] , "*":[["B","A","A'"],["#"]] , "/":[["B","A","A'"],["#"]] , "%":[["B","A","A'"],["#"]]},
    "P'":{"(":["D","P''"], "T_Id":["D","P''"] , "T_Decimal":["D","P''"] , "T_Hexadecimal":["D","P''"] , "T_String":["D","P''"] , "T_Character":["D","P''"] , "T_True":["D","P''"] , "T_False":["D","P''"] , "+":["D","P''"] , "-":["D","P''"] ,"!":["D","P''"] },
    "P''":{"||":["||","D","P''"],";":["#"], "]":["#"], ")":["#"] ,  ",":["#"]},
    "D":{"(":["E","D'"], "T_Id":["E","D'"] , "T_Decimal":["E","D'"] , "T_Hexadecimal":["E","D'"] , "T_String":["E","D'"] , "T_Character":["E","D'"] , "T_True":["E","D'"] , "T_False":["E","D'"] , "+":["E","D'"] , "-":["E","D'"] ,"!":["E","D'"]},
    "D'":{"&&":["&&","E","D'"],"||":["#"] ,  ";":["#"] , "]":["#"] , ")":["#"] , ",":["#"]},
    "E":{"(":["G","E'"], "T_Id":["G","E'"] , "T_Decimal":["G","E'"] , "T_Hexadecimal":["G","E'"] , "T_String":["G","E'"] , "T_Character":["G","E'"] , "T_True":["G","E'"] , "T_False":["G","E'"] , "+":["G","E'"] , "-":["G","E'"] ,"!":["G","E'"]},
    "G":{"(":["I","G'"], "T_Id":["I","G'"] , "T_Decimal":["I","G'"] , "T_Hexadecimal":["I","G'"] , "T_String":["I","G'"] , "T_Character":["I","G'"] , "T_True":["I","G'"] , "T_False":["I","G'"] , "+":["I","G'"] , "-":["I","G'"] ,"!":["I","G'"]},
    "E'":{"==":["F","G","E'"] , "!=":["F","G","E'"],"&&":["#"] , "||":["#"] , ";":["#"] , "]":["#"] , ")":["#"] , ",":["#"]},
    "F":{"==":["=="] , "!=":["!="]},
    "I":{"(":["K","I'"], "T_Id":["K","I'"] , "T_Decimal":["K","I'"] , "T_Hexadecimal":["K","I'"] , "T_String":["K","I'"] , "T_Character":["K","I'"] , "T_True":["K","I'"] , "T_False":["K","I'"] , "+":["K","I'"] , "-":["K","I'"] ,"!":["K","I'"]},
    "G'":{"<":["H","I","G'"] , "<=":["H","I","G'"] , ">":["H","I","G'"] , ">=":["H","I","G'"],"==":["#"] , "!=":["#"] , "&&":["#"] , "||":["#"] , ";":["#"] , "]":["#"] , ")":["#"] , ",":["#"]},
    "H":{"<":["<"] , "<=":["<="] , ">":[">"] , ">=":[">="]},
    "K":{"(":["M","K'"], "T_Id":["M","K'"] , "T_Decimal":["M","K'"] , "T_Hexadecimal":["M","K'"] , "T_String":["M","K'"] , "T_Character":["M","K'"] , "T_True":["M","K'"] , "T_False":["M","K'"] , "+":["M","K'"] , "-":["M","K'"] ,"!":["M","K'"]},
    "I'":{"+":["J","K","I'"] , "-":["J","K","I'"],"<":["#"] ,"<=":["#"] , ">":["#"] , ">=":["#"] , "==":["#"] , "!=":["#"] , "&&":["#"] ,"||":["#"] , ";":["#"]  , "]":["#"] , ")":["#"] , ",":["#"] },
    "J":{"+":["+"] , "-":["-"]},
    "M":{"(":["(","S",")"], "T_Id":["T_Id","M'"] , "T_Decimal":["T_Decimal"] , "T_Hexadecimal":["T_Hexadecimal"] , "T_String":["T_String"] , "T_Character":["T_Character"] , "T_True":["T_True"] , "T_False":["T_False"] , "+":["N","T_Id"] , "-":["N","T_Id"] ,"!":["!","M"]},
    "M'":{"(":["(","Q",")"], "+":[["N"],["#"]] , "-":[["N"],["#"]],"<":["#"] ,"<=":["#"] , ">":["#"] , ">=":["#"] , "==":["#"] , "!=":["#"] , "&&":["#"] ,"||":["#"] , ";":["#"]  , "]":["#"] , ")":["#"] , ",":["#"] , "*":["#"], "/":["#"] , "%":["#"]},
    "N":{"+":["+","+"],"-":["-","-"]},
    "K'":{"*":["L","M","K'"] , "/":["L","M","K'"] , "%":["L","M","K'"] , "+":["#"],"-":["#"],"<":["#"] ,"<=":["#"] , ">":["#"] , ">=":["#"] , "==":["#"] , "!=":["#"] , "&&":["#"] ,"||":["#"] , ";":["#"]  , "]":["#"] , ")":["#"] , ",":["#"] },
    "L":{"*":["*"] , "/":["/"] , "%":["%"]},
    "Q":{"T_Id":["R","T"] , "T_Decimal":["R","T"] , "T_Hexadecimal":["R","T"] , "T_String":["R","T"] , "T_Character":["R","T"] , "T_True":["R","T"] , "T_False":["R","T"],")":["#"]},
    "R":{"T_Id":["T_Id"] , "T_Decimal":["T_Decimal"] , "T_Hexadecimal":["T_Hexadecimal"] , "T_String":["T_String"] , "T_Character":["T_Character"] , "T_True":["T_True"] , "T_False":["T_False"]},
    "T":{",":[",","R","T"],")":["#"]},
    "Def":{"[":["Var"] , "=":["Var"] , ",":["Var"] , ";":["Var"] , "(":["Function"]},
    "Var":{"[":["U","W",";"] , "=":["U","W",";"] , ",":["U","W",";"] , ";":["U","W",";"]},
    "U":{"[":["[","S","]"] , "=":["=","S"],",":["#"] , ";":["#"]},
    "W":{",":[",","Var"],";":["#"]},
    "IF":{"T_If":["T_If","(","S",")","X","Y","Z"]},
    "X":{"{":["{","a","}"],"(":["Statement"] , "!":["Statement"] , "T_Id":["Statement"] , "T_Decimal":["Statement"] , "T_Hexadecimal":["Statement"] , "T_String":["Statement"] , "T_Character":["Statement"] , "T_True":["Statement"] , "T_False":["Statement"], "+":["Statement"] , "-":["Statement"], ";":["Statement"] , "T_If":["Statement"] , "T_For":["Statement"] , "T_Bool":["Statement"] , "T_Int":["Statement"] , "T_Char":["Statement"],"T_Void":["Statement"]  , "T_Print":["Statement"]},
    "a":{"(":["Statement","a"] , "!":["Statement","a"] , "T_Id":["Statement","a"] , "T_Decimal":["Statement","a"] , "T_Hexadecimal":["Statement","a"] , "T_String":["Statement","a"] , "T_Character":["Statement","a"] , "T_True":["Statement","a"] , "T_False":["Statement","a"], "+":["Statement","a"] , "-":["Statement","a"], ";":["Statement","a"] , "T_If":["Statement","a"] , "T_For":["Statement","a"] , "T_Bool":["Statement","a"] , "T_Int":["Statement","a"] , "T_Char":["Statement","a"],"T_Void":["Statement","a"]  , "T_Print":["Statement","a"],"}":["#"]},
    "Y":{"T_Else":["T_Else","T_If","(","S",")","X","Y"],"(":["#"], "!":["#"]  , "T_Id":["#"] , "T_Decimal":["#"] , "T_Hexadecimal":["#"] , "T_String":["#"] , "T_Character":["#"] , "T_True":["#"] , "T_False":["#"], "+":["#"] , "-":["#"] , ";":["#"] , "T_If":["#"] , "T_For":["#"] , "T_Bool":["#"] , "T_Int":["#"] , "T_Char":["#"],"T_Void":["#"]  , "T_Print":["#"] , "T_Else":["#"] , "T_Return":["#"] , "T_Break":["#"] , "T_Continue":["#"],"}":["#"], "$":["#"]},
    "Z":{"T_Else":["T_Else","X"],"(":["#"], "!":["#"]  , "T_Id":["#"] , "T_Decimal":["#"] , "T_Hexadecimal":["#"] , "T_String":["#"] , "T_Character":["#"] , "T_True":["#"] , "T_False":["#"], "+":["#"] , "-":["#"] , ";":["#"] , "T_If":["#"] , "T_For":["#"] , "T_Bool":["#"] , "T_Int":["#"] , "T_Char":["#"],"T_Void":["#"]  , "T_Print":["#"] , "T_Return":["#"] , "T_Break":["#"] , "T_Continue":["#"],"}":["#"], "$":["#"]},
    "For":{"T_For":["T_For","(","h",";","i",";","i",")","j"]},
    "h":{"T_Int":["Type","T_Id","h'"] , "T_Char":["Type","T_Id","h'"] , "T_Bool":["Type","T_Id","h'"] , "T_Void":["Type","T_Id","h'"] , "(":["S"],"T_Id":["S"] , "T_Decimal":["S"] , "T_Hexadecimal":["S"] , "T_String":["S"] , "T_Character":["S"] , "T_True":["S"] , "T_False":["S"] , "+":["S"] , "-":["S"], "!":["S"],";":["#"]},
    "h'":{"=":["=","S"],";":["#"]},
    "i":{"(":["S"], "T_Id":["S"] , "T_Decimal":["S"] , "T_Hexadecimal":["S"] , "T_String":["S"] , "T_Character":["S"] , "T_True":["S"] , "T_False":["S"] , "+":["S"] , "-":["S"], "!":["S"],";":["#"],")":["#"]},
    "j":{"{":["{","k","}"],"T_Break":["LCommands"] , "T_Continue":["LCommands"]  , "(":["Statement"], "!":["Statement"]  , "T_Id":["Statement"] , "T_Decimal":["Statement"] , "T_Hexadecimal":["Statement"] , "T_String":["Statement"] , "T_Character":["Statement"] , "T_True":["Statement"] , "T_False":["Statement"], "+":["Statement"] , "-":["Statement"] , ";":["Statement"] , "T_If":["Statement"] , "T_For":["Statement"] , "T_Bool":["Statement"] , "T_Int":["Statement"] , "T_Char":["Statement"],"T_Void":["Statement"]  , "T_Print":["Statement"]},
    "LCommands":{"T_Break":["LCommands"],"T_Continue":["LCommands"]},
    "z":{"T_Break":["LCommands"] , "T_Continue":["LCommands"]   , "(":["S"], "!":["S"]  , "T_Id":["S"] , "T_Decimal":["S"] , "T_Hexadecimal":["S"] , "T_String":["S"] , "T_Character":["S"] , "T_True":["S"] , "T_False":["S"], "+":["S"] , "-":["S"] , ";":["S"] , "T_If":["T_If","(","S",")","X'","Y'","Z'"] , "T_For":["For"] , "T_Bool":["Type","T_Id","Var"] , "T_Int":["Type","T_Id","Var"] , "T_Char":["Type","T_Id","Var"],"T_Void":["Type","T_Id","Var"]  , "T_Print":["Print",";"]},
    "k":{"T_Break":["z","k"] , "T_Continue":["z","k"]   , "(":["z","k"], "!":["z","k"]  , "T_Id":["z","k"] , "T_Decimal":["z","k"] , "T_Hexadecimal":["z","k"] , "T_String":["z","k"] , "T_Character":["z","k"] , "T_True":["z","k"] , "T_False":["z","k"], "+":["z","k"] , "-":["z","k"] , ";":["z","k"] , "T_If":["z","k"] , "T_For":["z","k"] , "T_Bool":["z","k"] , "T_Int":["z","k"] , "T_Char":["z","k"],"T_Void":["z","k"]  , "T_Print":["z","k"],"}":["#"]},
    "X'":{"(":["Statement"] , "!":["Statement"] , "T_Id":["Statement"] , "T_Decimal":["Statement"] , "T_Hexadecimal":["Statement"] , "T_String":["Statement"] , "T_Character":["Statement"] , "T_True":["Statement"] , "T_False":["Statement"], "+":["Statement"] , "-":["Statement"], ";":["Statement"] , "T_If":["Statement"] , "T_For":["Statement"] , "T_Bool":["Statement"] , "T_Int":["Statement"] , "T_Char":["Statement"],"T_Void":["Statement"]  , "T_Print":["Statement"],"{":["{","a'","}"],"T_Break":["LCommands"],"T_Continue":["LCommands"]},
    "a'":{"(":["Statement","a'"] , "!":["Statement","a'"] , "T_Id":["Statement","a'"] , "T_Decimal":["Statement","a'"] , "T_Hexadecimal":["Statement","a'"] , "T_String":["Statement","a'"] , "T_Character":["Statement","a'"] , "T_True":["Statement","a'"] , "T_False":["Statement","a'"], "+":["Statement","a'"] , "-":["Statement","a'"], ";":["Statement","a'"] , "T_If":["Statement","a'"] , "T_For":["Statement","a'"] , "T_Bool":["Statement","a'"] , "T_Int":["Statement","a'"] , "T_Char":["Statement","a'"],"T_Void":["Statement","a'"]  , "T_Print":["Statement","a'"],"T_Break":["LCommands","a'"],"T_Continue":["LCommands","a'"],"}":["#"]},
    "Y'":{"T_Else":["T_Else","T_If","(","S",")","X'","Y'"],"(":["#"], "!":["#"]  , "T_Id":["#"] , "T_Decimal":["#"] , "T_Hexadecimal":["#"] , "T_String":["#"] , "T_Character":["#"] , "T_True":["#"] , "T_False":["#"], "+":["#"] , "-":["#"] , ";":["#"] , "T_If":["#"] , "T_For":["#"] , "T_Bool":["#"] , "T_Int":["#"] , "T_Char":["#"],"T_Void":["#"]  , "T_Print":["#"] , "T_Else":["#"] , "T_Return":["#"] , "T_Break":["#"] , "T_Continue":["#"],"}":["#"], "$":["#"]},
    "Z'":{"T_Else":["T_Else","X'"],"(":["#"], "!":["#"]  , "T_Id":["#"] , "T_Decimal":["#"] , "T_Hexadecimal":["#"] , "T_String":["#"] , "T_Character":["#"] , "T_True":["#"] , "T_False":["#"], "+":["#"] , "-":["#"] , ";":["#"] , "T_If":["#"] , "T_For":["#"] , "T_Bool":["#"] , "T_Int":["#"] , "T_Char":["#"],"T_Void":["#"]  , "T_Print":["#"] , "T_Return":["#"] , "T_Break":["#"] , "T_Continue":["#"],"}":["#"], "$":["#"]},
    "Function":{"(":["(","b",")","c"]},
    "b":{"T_Int":["Type","T_Id","e","f"],"T_Bool":["Type","T_Id","e","f"],"T_Char":["Type","T_Id","e","f"],"T_String":["Type","T_Id","e","f"],")":["#"]},
    "e":{"[":["[","]"],")":["#"],",":["#"]},
    "f":{",":[",","Type","T_Id","e","f"],")":["#"]},
    "c":{";":[";"],"{":["{","d","}"]},
    "d":{"T_Return":["T_Return","d'"],"(":["Statement","d"] , "!":["Statement","d"] , "T_Id":["Statement","d"] , "T_Decimal":["Statement","d"] , "T_Hexadecimal":["Statement","d"] , "T_String":["Statement","d"] , "T_Character":["Statement","d"] , "T_True":["Statement","d"] , "T_False":["Statement","d"], "+":["Statement","d"] , "-":["Statement","d"], ";":["Statement","d"] , "T_If":["Statement","d"] , "T_For":["Statement","d"] , "T_Bool":["Statement","d"] , "T_Int":["Statement","d"] , "T_Char":["Statement","d"],"T_Void":["Statement","d"]  , "T_Print":["Statement","d"],"}":["#"]},
    "d'":{";":[";","d"],"(":["S",";","d"], "T_Id":["S",";","d"] , "T_Decimal":["S",";","d"] , "T_Hexadecimal":["S",";","d"] , "T_String":["S",";","d"] , "T_Character":["S",";","d"] , "T_True":["S",";","d"] , "T_False":["S",";","d"] , "+":["S",";","d"] , "-":["S",";","d"], "!":["S",";","d"]},
    "Print":{"T_Print":["T_Print","(","S","g",")"]},
    "g":{",":[",","S","g"],")":["#"]}

}

// A'   S     M'       N




export {paresrTable}